name: Build New Version

on:
  schedule:
    - cron: 0 0 * * 5
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract latest available PrusaSlicer Version
        id: version
        run: echo "version=$(sh get_release_info.sh version)" |tee -a $GITHUB_OUTPUT

      - name: Check if this release already exists
        uses: mukunku/tag-exists-action@v1.2.0
        id: checktag
        with:
          tag: ${{ steps.version.outputs.version }}

      - name: Create new tag with PrusaSlicer Version
        uses: rickstaa/action-create-tag@v1
        id: tag_create
        if: ${{ steps.checktag.outputs.exists == 'false' }}
        with:
          tag: ${{ steps.version.outputs.version }}
          tag_exists_error: false
          message: New PrusaSlicer Release ${{ steps.version.outputs.version }}

      - name: Build and push Container
        uses: docker/build-push-action@v4
        if: ${{ steps.checktag.outputs.exists == 'false' }}
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest, ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.version.outputs.version }}
      - name: release
        id: release
        if: ${{ steps.checktag.outputs.exists == 'false' }}
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "README.md"
          tag: ${{ steps.version.outputs.version }}
